### ISSUE TITLE
Several errors on Ubuntu 24.4 with gedit 46.2

### ISSUE THREAD

**Issue by FerdiScholten** [Maestroschan/gedit-plugin-markdown_preview#61]
First Ubuntu 24.4 does not have gir1.2-webkit2-4.0 it has been upgraded to gir1.2-webkit2-4.1 causing the plugin to fail to load:

> 
> ** (gedit:135002): WARNING **: 07:46:22.540: Error importing plugin 'markdown_preview':
> Traceback (most recent call last):
>   File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
>   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
>   File "/usr/lib/x86_64-linux-gnu/gedit/plugins/markdown_preview/__init__.py", line 7, in <module>
>     from .main_container import MdMainContainer
>   File "/usr/lib/x86_64-linux-gnu/gedit/plugins/markdown_preview/main_container.py", line 7, in <module>
>     from .webview_manager import MdWebViewManager
>   File "/usr/lib/x86_64-linux-gnu/gedit/plugins/markdown_preview/webview_manager.py", line 5, in <module>
>     gi.require_version('WebKit2', '4.0')
>   File "/usr/lib/python3/dist-packages/gi/__init__.py", line 125, in require_version
>     raise ValueError('Namespace %s not available for version %s' %
> ValueError: Namespace WebKit2 not available for version 4.0
> 

After changing the dependency to gir1.2-webkit2-4.1 the plugin loads but does not work, the panel remains empty and the following traceback is shown (probably same issue as #60):

> Traceback (most recent call last):
>   File "/usr/lib/x86_64-linux-gnu/gedit/plugins/markdown_preview/__init__.py", line 93, in do_activate
>     self.preview.do_activate()
>   File "/usr/lib/x86_64-linux-gnu/gedit/plugins/markdown_preview/main_container.py", line 52, in do_activate
>     self.build_preview_ui()
>   File "/usr/lib/x86_64-linux-gnu/gedit/plugins/markdown_preview/main_container.py", line 207, in build_preview_ui
>     self.show_on_panel()
>   File "/usr/lib/x86_64-linux-gnu/gedit/plugins/markdown_preview/main_container.py", line 463, in show_on_panel
>     self.panel.add_titled(self.preview_bar, 'markdown_preview', _("Markdown Preview"))
>     ^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'PanelContainer' object has no attribute 'add_titled'
> Traceback (most recent call last):
>   File "/usr/lib/x86_64-linux-gnu/gedit/plugins/markdown_preview/__init__.py", line 101, in do_update_state
>     self.preview.do_update_state()
>   File "/usr/lib/x86_64-linux-gnu/gedit/plugins/markdown_preview/main_container.py", line 70, in do_update_state
>     elif self.panel.get_visible_child() != self.preview_bar:
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'PanelContainer' object has no attribute 'get_visible_child'
> Traceback (most recent call last):
>   File "/usr/lib/x86_64-linux-gnu/gedit/plugins/markdown_preview/__init__.py", line 104, in do_deactivate
>     self.preview.do_deactivate()
>   File "/usr/lib/x86_64-linux-gnu/gedit/plugins/markdown_preview/main_container.py", line 86, in do_deactivate
>     self._delete_temp_file()
>   File "/usr/lib/x86_64-linux-gnu/gedit/plugins/markdown_preview/main_container.py", line 91, in _delete_temp_file
>     if self.temp_file_md.query_exists():
>        ^^^^^^^^^^^^^^^^^
> AttributeError: 'MdMainContainer' object has no attribute 'temp_file_md'

**Comment by ChrisJones79** [comment]
No way to use this with webkit2-4.1?

**Comment by danhilu** [comment]
Dear team, same as I also would have loved to use this plugin with gedit 46.2 on Ubuntu 24.4 and the plugin activation is greyed out. And "gir1.2-webkit2-4.0 is not available". Thank you!
